[build]
  command = """
  bash scripts/setup_julia.sh
  julia --project=. -e 'using Pkg; Pkg.instantiate(); include("julia/build_blog.jl")'
  npm run build
  """
  publish = "dist"

[[redirects]]
  from = "/rss.xml"
  to = "/rss.xml"
  status = 200

[build.environment]
  JULIA_NUM_THREADS = "2"
  NODE_VERSION = "20"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
